# Generated by Django 4.1 on 2022-08-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0002_note_category_note_description_note_image'),
        ('genders', '0001_initial'),
        ('brands', '0001_initial'),
        ('accords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('released', models.DateField(blank=True)),
                ('image', models.URLField(max_length=2000)),
                ('accord', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accords.accord')),
                ('base_notes', models.ManyToManyField(related_name='perfumes_base', to='notes.note')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='brands.brand')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='genders.gender')),
                ('mid_notes', models.ManyToManyField(related_name='perfumes_mid', to='notes.note')),
                ('top_notes', models.ManyToManyField(related_name='perfumes_top', to='notes.note')),
            ],
        ),
    ]
