version: '3.8'

services:
  db:
    restart: always
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scentseeker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5432
    
  backend:
    restart: always
    container_name: backend
    volumes:
      - .:/Users/Jacqueline/Development/Scent-Seeker/
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_NAME=scentseeker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    restart: always
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
