# Generated by Django 4.1 on 2022-08-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_categories', '0002_alter_note_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
