# Generated by Django 4.1 on 2022-08-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accord',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
