# Generated by Django 4.1 on 2022-08-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfume_category',
            options={'verbose_name': 'Perfume Category', 'verbose_name_plural': 'Perfume Categories'},
        ),
    ]
