# Generated by Django 4.1 on 2022-08-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note_categories', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='note_categories.note_category'),
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.URLField(default=None, max_length=2000),
        ),
    ]
